# Generated by Django 6.0.5 on 2026-05-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='hyd'),
        ),
    ]
